name: nuraga_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/font/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-ExtraBold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 800
        - asset: assets/font/Poppins-Bold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 700
        - asset: assets/font/Poppins-SemiBold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 600
        - asset: assets/font/Poppins-Medium.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 400
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
